name: Deploy to Azure the 'dev' version
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: deploy to Azure
      run: |
        az deployment sub create -n rust-app-deployment --location francecentral --template-file subscription.bicep \
          --parameters hashSecret=$HASH_SECRET jwtSecret=$JWT_SECRET databaseUrl=$DATABASE_URL registryPassword=$READ_PACKAGE_PAT
